# Generated by Django 3.1.7 on 2021-05-07 06:31

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import oceanswave.yandex_s3_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('cities', models.ManyToManyField(blank=True, null=True, to='main.City')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('teacher', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('places_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('image', models.FileField(blank=True, null=True, storage=oceanswave.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
                ('source_link', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField(default='')),
                ('count_of_lections', models.IntegerField(default=0)),
                ('image', models.FileField(blank=True, null=True, storage=oceanswave.yandex_s3_storage.ClientDocsStorage(), upload_to='')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
