# Generated by Django 3.1.7 on 2021-05-10 13:34

from django.db import migrations, models
import oceanswave.yandex_s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210510_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_image',
            field=models.FileField(blank=True, null=True, storage=oceanswave.yandex_s3_storage.ClientDocsStorage(), upload_to=''),
        ),
    ]
