# Generated by Django 3.1.7 on 2021-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='telegram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='specialist',
            name='whatsapp',
            field=models.TextField(default=''),
        ),
    ]
