# Generated by Django 3.1.7 on 2021-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_specialist_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
