# Generated by Django 3.1.7 on 2021-05-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='qr_image',
        ),
    ]
