# Generated by Django 3.1.7 on 2021-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
