# Generated by Django 3.1.7 on 2021-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210525_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
