# Generated by Django 3.1.7 on 2021-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210525_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
